language: java
script:
- bash create_config.sh
- export projects_dir=$(pwd)
- export expected_product_count=5
- cd $projects_dir/python2 && sudo pip install -r requirements.txt && ./hello-api | grep "MB PREMIUM TECH T"
- cd $projects_dir/python3 && sudo apt-get install python3-setuptools && sudo easy_install3 pip && sudo pip install -r requirements.txt && ./hello-api | grep "MB PREMIUM TECH T"
- cd $projects_dir/curl && sudo apt-get install jq && ./hello-api | grep $expected_product_count
- cd $projects_dir/java && ./gradlew run
- cd $projects_dir/scala && sbt run | grep 'Number of products'
- 'cd $projects_dir/javascript && npm install -g grunt-cli casperjs && npm install && ./bin/get_token --client_id "${CLIENT_ID}" --client_secret "${CLIENT_SECRET}" --project_key "${PROJECT_KEY}" && grunt test'
- cd $projects_dir/php && sudo apt-get install php5 && php -f index.php | grep -q "MB PREMIUM TECH T"
- cd $projects_dir/go && go get github.com/jmoiron/jsonq && go build hello.go && ./hello | grep $expected_product_count
jdk:
- openjdk6
- openjdk7
- oraclejdk7
- oraclejdk8
env:
  global:
  - secure: ISBTx5dCLRYtT+vp5MXFiZoJMF9l/I+W40fCIGp/OYJVm5uX3QdY9tqmPPJtHyGNYC/U2MNrhg/Z+8opwxQ931e9kCUfg/7nk6EX8t0gYV4tMKkaqr+NJ7S7uyu8SrFbcwABzUo5/91ujKkrsp/R5yQ/kCggDND+utpEVSWB9LY=
  - secure: cTja//s9O9IYrCOgjeFp4j0MJzVfjCnADlF69hPQsLaJNAPAGc6JRcUeaOeVZHSMI3y3qh4IGgfAm3QuxyUFTn5RP0OVpDAYri29Ubn7SYA55cho7K+YUZbrnCFuFMypZ8dVVbdZA2cFefUUnVhuGXHFlVUWUPUwUFd0o2oSw5Y=
  - secure: j3EAxprAcKq4aaGn/WA9VKn41C9Kismp/I0caLWP6k2dZvk1SZGnaiZXuAeqLxQMQ4cU4WH6qupnxCb/oS+0OxIe6UE7QAM7Xk8e5jp52NTubCkBJH04gi3BSVapLtDK1ePerNJuwOo0LZh9hwGwMWGy2XEZe59B5V50vvyp8Qo=
